engines:
  pmd:
    enabled: true
    channel: "beta"
ratings:
   paths:
   - "TextFieldBoxes/textfieldboxes/src/main/java/studio/carbonylgroup/textfieldboxes/"
   - "TextFieldBoxes.java"
   - "PanelView.java"
   - "Utils.java"
